version: "2"

run:
  tests: false

linters:
  enable:
    - asciicheck
    - errname
    - exhaustive
    - gocritic
    - makezero
    - misspell
    - thelper
    - unconvert
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

  settings:
    staticcheck:
      checks:
        - all
        - '-ST1005' # ST1005: error strings should not be capitalized

formatters:
  enable:
    - goimports
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters-settings:
  goimports:
    local-prefixes: github.com/devbuddy/devbuddy
