run:
  tests: false

linters:
  enable:
    - asciicheck
    - errname
    # - errorlint
    - exhaustive
    - gci
    - gocritic
    - gofmt
    - makezero
    - misspell
    - tenv
    - thelper
    - unconvert
    - wastedassign
    - durationcheck
    # - err113
    - asasalint
    - asciicheck
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - errchkjson
    - errname
    - exhaustive
    - fatcontext


linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/devbuddy/devbuddy)
