up:
  - go: 1.10.1
  - golang_dep
  - python: 3.6.5
  - pip: [tests/requirements.txt]
  - homebrew:
    - curl
  - custom:
      name: Install shellcheck
      met?: test -e /usr/local/Cellar/shellcheck
      meet: brew install shellcheck

commands:
  testup:
    desc: Build, install and run the development version
    run: go install && bud up

  test:
    desc: Run the unittests
    run: script/test

  integration:
    desc: Run the integration tests with Bash
    run: pytest -v tests

  integration-zsh:
    desc: Run the integration tests with Zsh
    run: pytest --shell zsh -v tests

  lint:
    desc: Lint the project
    run: script/lint

  lint-shell:
    desc: Lint the shell scripts
    run: shellcheck script/*

  ci:
    desc: Run all tests as CI would do
    run: script/test && pytest -v tests && script/lint

  release:
    desc: Create a new release (bud release [VERSION])
    run: script/release

  godoc:
    desc: Starting GoDoc server on http://0.0.0.0:6060
    run: (sleep 1; open http://0.0.0.0:6060)& godoc -http=:6060

  install-dev:
    desc: Install bud in the GOROOT
    run: |
      go build -ldflags "-X main.Version=$(git describe --tags --dirty --always)" -o $GOPATH/bin/bud
      [ -e "/usr/local/bin/bud" ] && sudo rm /usr/local/bin/bud || true

  install-release:
    desc: Remove all bud binaries and install a released version
    run: |
      [ -e "/usr/local/bin/bud" ] && sudo rm -v /usr/local/bin/bud
      [ -e "$GOPATH/bin/bud" ] && sudo rm -v $GOPATH/bin/bud
      bash -c "$(curl -sL https://raw.githubusercontent.com/devbuddy/devbuddy/master/install.sh)"

  build:
    desc: Build all bud binaries
    run: script/buildall

open:
  milestone: https://github.com/devbuddy/devbuddy/milestone/1
