up:
  - go: 1.10.1
  - golang_dep
  - custom:
      met?: test -e /usr/local/Cellar/shellcheck
      meet: brew install shellcheck

commands:
  testup:
    desc: Build, install and run the development version
    run: go install && dad up

  test:
    desc: Run the unittests
    run: script/test

  integration:
    desc: Run the integration tests
    run: script/integration_test

  lint:
    desc: Lint the project
    run: script/lint

  lint-shell:
    desc: Lint the shell scripts
    run: shellcheck script/* tests/*.sh

  ci:
    desc: Run all tests as CI would do
    run: script/test && script/integration_test && script/lint

  release:
    desc: Create a new release (dad release [VERSION])
    run: script/release

  godoc:
    desc: Starting GoDoc server on http://0.0.0.0:6060
    run: (sleep 1; open http://0.0.0.0:6060)& godoc -http=:6060

  install-dev:
    desc: Install dad in the GOROOT
    run: |
      go install -ldflags "-X main.Version=$(git describe --tags --dirty --always)"
      [ -e "/usr/local/bin/dad" ] && sudo rm /usr/local/bin/dad || true

  install-release:
    desc: Remove all dad binaries and install a released version
    run: |
      [ -e "/usr/local/bin/dad" ] && sudo rm -v /usr/local/bin/dad
      [ -e "$GOPATH/bin/dad" ] && sudo rm -v $GOPATH/bin/dad
      bash -c "$(curl -sL https://raw.githubusercontent.com/pior/dad/master/install.sh)"
