
[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/dnaeon/go-vcr"

[[constraint]]
  name = "github.com/sahilm/fuzzy"
  version = "0.0.5"
