#!/bin/sh
set -eu

TAG=$(git describe --tags --dirty --always)
DATE=$(date -u)
VERSION="${TAG} [${DATE}]"
LDFLAGS="-s -w -X \"main.Version=${VERSION}\""

for GOOS in linux darwin; do
	export GOOS
	NAME=dad-${GOOS}-amd64

	echo "Building $NAME"
	GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "$LDFLAGS" -o dist/${NAME}
	shasum -a 256 dist/${NAME} > dist/${NAME}.sha256
done
