#!/usr/bin/env bash
set -euo pipefail

title() {
    echo -e "\n\n#--------------------------------------------"
    echo -e "# $@"
    echo -e "#"
}

setup_environment() {
    echo " -> Build the project."
    go build -o bud

    echo " -> Adding the current dir to PATH."
    ROOT=$PWD
    export PATH="$ROOT:$PATH"

    if [[ "$(which bud)" != "$ROOT/bud" ]]; then
        echo "In order to run the integration test on the current code,"
        echo "the locally built bud binary must be found in the PATH."
        echo "But 'which bud' returned: $(which bud)"
        exit 1
    fi
}

run_tests() {
    local failures=()
    local -r shell=$1

    title "Running tests with $shell"

    for testfile in *_test.sh; do
        echo -e "\nRunning: ${testfile}"
        $shell ${testfile} || failures+=(${testfile})
    done

    if [[ ${#failures[@]} -ne 0 ]]; then
        title "REPORT: the following tests failed! ❌"

        for failure in "${failures[@]}"; do
            echo "Failed: $failure ❌"
        done
        return 1
    fi

    echo -e "\nAll tests passed successfully: ✅"
}

main() {
    setup_environment

    cd "$ROOT/tests"

    local exitcode=0

    run_tests "bash" || exitcode=1
    run_tests "zsh -o shwordsplit" || exitcode=1

    exit $exitcode
}

main
