#!/bin/sh
set -eu

gometalinter.v2 \
    --vendor \
    --deadline=120s \
    --disable=gotype \
    --disable=gas --disable=gosec \
    --enable=gofmt \
    --exclude=".*should have comment or be unexported.*" \
    ./...
