#!/bin/bash
set -xe

go get -u github.com/golang/dep/cmd/dep
dep ensure

if [ "$1" == "test" ]; then
    go get -u gopkg.in/alecthomas/gometalinter.v2
    gometalinter.v2 --install --update
fi

sudo apt-get install upx
